---
- name: Update apt cache
  apt: update_cache=yes

- name: Install apt dependencies
  apt: name={{ item }}
  with_items:
    - build-essential
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
    - python-dev
