---
- name: Update apt cache
  apt: update_cache=yes
  become: yes
  become_user: root

- name: Install apt dependencies
  apt: name={{ item }}
  with_items:
    - build-essential
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
    - python-dev
  become: yes
  become_user: root
